### PR TITLE
Enable testing with molecule

### PR DESCRIPTION
**Pull request by brucellino**
Just a minor fix to the tasks file, which was failing PEP8 tests

### CODE REVIEW

**Comment by brucellino** [comment]
Ok, I've added a bunch more things to this pull request. No functionality has changed, I've just enabled testing with molecule.

**Comment by brucellino** [comment]
Now with tests.

**Comment by brucellino** [comment]
@orviz can you please review these changes and let me know if we can merge ?

**Comment by orviz** [comment]
@brucellino now that PR builder has been set up in Jenkins, could you set up a job to run molecule as part of the checks?

**Comment by brucellino** [comment]
This is beautiful.... standby and thanks !

**Comment by orviz** [comment]
@brucellino If travis is going to be used here, does it make sense to have Jenkins triggered here?

**Comment by brucellino** [comment]
Hey @orviz 

I agree that only one should be used. Having more than one is fine though, since there is zero work to have things tested in travis - it's just a config file after all - but it's an optional. We _must_ have things in Jenkins so that we can build complete pipelines. Long term, I think we'll have everything only on Jenkins.

**Comment by orviz** [comment]
anyway the tests now triggered in Jenkins are dummy ones, just to check the PR builder plugin. We need then to configure them to use molecule the same way travis does
Approving this

**Pull request merged**
